### PR TITLE
Edited to use SASS

### PR DESCRIPTION
**Pull request by 7coil**
uwu hiii it's katie it looks like you fucked up! uh oh! ^_^ but i fixy wixy 4 u

Aaaaa~ I put `<html>` tags 4 u and used SASS :3

### CODE REVIEW

**Comment by Ratismal** [comment]
delete this, this is nsfw, it's offending my eyes!!!!!!!!!!!!!!!!!!!!!!!

**Comment by 7coil** [comment]
Fixed merge conflicts

**Comment by lepon01** [comment]
uwu

**Comment by Ratismal** [comment]
excuse me can you not send me nsfw images to my mail inbox??!?!

**Comment by lepon01** [comment]
NANI?!?

**Comment by Ratismal** [comment]
:c but the merge...

**Pull request closed without merging**
